name: locale_gen_annotation
description: An annotation companion package for locale_gen
version: 1.0.1
repository: https://github.com/oquad/locale_gen

environment:
  sdk: ^3.4.3

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  lints: ^3.0.0
  test: ^1.24.0
