name: locale_gen_annotation
description: An annotation companion package for locale_gen
version: 1.0.4
repository: https://github.com/oquad/locale_gen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.4'

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^4.0.0
