name: locale_generator
description: Generates dart code for locales
version: 1.0.0
repository: https://github.com/oquad/locale_gen

environment:
  sdk: ^3.4.3

dependencies:
  build: ^2.4.1
  collection: ^1.18.0
  freezed_annotation: ^2.4.4
  meta: ^1.12.0
  source_gen: ^1.5.0
  locale_gen_annotation: ^1.0.0
  analyzer: ^6.4.0
  build_runner: ^2.4.11
  json_annotation: ^4.9.0

dev_dependencies:
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
