name: locale_generator
description: Generates dart code for locales
version: 1.0.6
repository: https://github.com/oquad/locale_gen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.4'

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.4.1
  build: ^2.4.1
  build_runner: ^2.4.9
  collection: ^1.18.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  locale_gen_annotation: ^1.0.3
  source_gen: ^1.5.0
  meta: ^1.11.0

dev_dependencies:
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lints: ^4.0.0
