name: locale_generator
description: Generates dart code for locales
version: 1.2.0
repository: https://github.com/oquad/locale_gen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.4'

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^8.0.0
  build: ^4.0.2
  build_runner: ^2.10.2
  collection: ^1.18.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  locale_gen_annotation: 1.2.0
  source_gen: ^4.0.0
  meta: ^1.11.0

dev_dependencies:
  freezed: ^3.2.0
  json_serializable: ^6.8.0
  lints: ^4.0.0
